services:
  api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env.development
