version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emas-api
    restart: unless-stopped
    env_file:
      - ./.env # taruh semua env prod di sini
    ports:
      - '3001:3001'
    environment:
      # jaga-jaga override jika perlu
      NODE_ENV: development
      TZ: Asia/Jakarta
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:3001/csrf-token >/dev/null 2>&1 || exit 1']
      interval: 30s
      timeout: 5s
      retries: 5
